import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — Habesha Homes',
  description: 'Terms of Service for Habesha Homes Ethiopian property marketplace',
}

export default function TermsPage() {
  return (
    <div style={{ background: '#fff', minHeight: '100vh' }}>
      {/* Header */}
      <div style={{ background: '#0d2318', padding: '48px 24px' }}>
        <div style={{ maxWidth: 760, margin: '0 auto' }}>
          <div style={{ display: 'flex', gap: 5, marginBottom: 20 }}>
            {['#078930','#FCDD09','#DA121A'].map(c => <div key={c} style={{ width: 28, height: 3, borderRadius: 2, background: c }}/>)}
          </div>
          <h1 style={{ fontSize: 36, fontWeight: 900, color: '#fff', margin: '0 0 8px', letterSpacing: '-.02em' }}>Terms of Service</h1>
          <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.5)', margin: 0 }}>Last updated: March 2026</p>
        </div>
      </div>

      {/* Content */}
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '48px 24px' }}>
        {[
          {
            title: '1. Acceptance of Terms',
            content: 'By accessing or using Habesha Homes ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services. These terms apply to all users including buyers, renters, agents, and visitors.'
          },
          {
            title: '2. Description of Service',
            content: 'Habesha Homes is an online real estate marketplace connecting property buyers, renters, and sellers in Ethiopia. We provide AI-powered tools including property valuations, fraud detection, contract analysis, and neighborhood reports powered by Anthropic\'s Claude AI.'
          },
          {
            title: '3. User Accounts',
            content: 'You must create an account to access certain features. You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate and complete information when creating your account. Habesha Homes reserves the right to suspend or terminate accounts that violate these terms.'
          },
          {
            title: '4. Property Listings',
            content: 'Agents and sellers are responsible for the accuracy of all listing information. Habesha Homes does not verify the accuracy of listings and is not responsible for errors or omissions. All listings are subject to review and approval. We reserve the right to remove listings that violate our policies or applicable Ethiopian law.'
          },
          {
            title: '5. AI Reports and Services',
            content: 'Our AI-powered reports (fraud detection, valuations, contract analysis) are provided for informational purposes only and do not constitute legal, financial, or professional advice. Results are generated by AI and may contain errors. Always consult qualified professionals before making property decisions. Reports are non-refundable once generated.'
          },
          {
            title: '6. Payments',
            content: 'Payments for AI reports are processed securely through Stripe. All prices are listed in USD. Habesha Homes does not store credit card information. Fees for AI reports are non-refundable once the report has been generated. Agent subscription fees are billed monthly and can be cancelled at any time.'
          },
          {
            title: '7. Prohibited Activities',
            content: 'You agree not to: post false or misleading property listings; use the platform for fraudulent transactions; scrape or copy our data; attempt to circumvent security measures; use the platform for illegal activities under Ethiopian law; harass other users or agents.'
          },
          {
            title: '8. Limitation of Liability',
            content: 'Habesha Homes is not liable for any property transactions conducted through the platform. We are a marketplace connecting buyers and sellers — all transactions are between the parties involved. We are not liable for losses arising from reliance on AI-generated reports.'
          },
          {
            title: '9. Privacy',
            content: 'Your use of Habesha Homes is also governed by our Privacy Policy, which is incorporated into these Terms. Please review our Privacy Policy to understand our data practices.'
          },
          {
            title: '10. Changes to Terms',
            content: 'We may update these Terms at any time. Continued use of the platform after changes constitutes acceptance of the new terms. We will notify registered users of significant changes via email.'
          },
          {
            title: '11. Governing Law',
            content: 'These Terms are governed by the laws of the Federal Democratic Republic of Ethiopia. Any disputes shall be resolved in the courts of Addis Ababa, Ethiopia.'
          },
          {
            title: '12. Contact',
            content: 'For questions about these Terms, contact us at legal@habeshahomes.com or visit our contact page.'
          },
        ].map(({ title, content }) => (
          <div key={title} style={{ marginBottom: 32 }}>
            <h2 style={{ fontSize: 18, fontWeight: 700, color: '#111', marginBottom: 10 }}>{title}</h2>
            <p style={{ fontSize: 15, color: '#555', lineHeight: 1.8, margin: 0 }}>{content}</p>
          </div>
        ))}

        <div style={{ borderTop: '1px solid #eae9e4', paddingTop: 32, marginTop: 16 }}>
          <p style={{ fontSize: 14, color: '#888', marginBottom: 16 }}>
            By using Habesha Homes you agree to these terms.
          </p>
          <div style={{ display: 'flex', gap: 12 }}>
            <Link href="/privacy" style={{ fontSize: 14, color: '#16a34a', textDecoration: 'none', fontWeight: 600 }}>Privacy Policy →</Link>
            <Link href="/contact" style={{ fontSize: 14, color: '#16a34a', textDecoration: 'none', fontWeight: 600 }}>Contact us →</Link>
          </div>
        </div>
      </div>
    </div>
  )
}
